
title: La Photosynthèse- moteur du vivant
email: shosana.20598@saintmicheldepicpus.fr
description: >-
  Bienvenue sur ce magnifique site web qui allie humour, cohésion de groupe et recherche scientifique pour expliquer le phénomène de la photosynthèse.  Ce projet a été réalisé dans le cadre d'une activité d'ES scientifique. Lycée: Saint-Michel de Picpus  Cours: ES SVT  Professeure: Mme Buttay  
baseurl: "/la-photosynthese" # the subpath of your site, e.g. /blog
url: "https://Hosana-sacha.github.io/laphotosyntheseSVT" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Hosana-sacha
instagram_username: sacha_hosana
linkedin_username: sacha-hosana
collections:
  projects:
    output: true
    permalink: /projects/:name/

exclude:
  - assets
  - images
  
include:
  - imageswebsite

paginate: 6
paginate_path: "/blog/page:num/"
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
